// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADFpi62QA9Xdnva0PFXlgWkErRfI-lBPU',
    appId: '1:372284465765:web:e6545e75d79ecc6db8dc8c',
    messagingSenderId: '372284465765',
    projectId: 'easy-shopping-f5166',
    authDomain: 'easy-shopping-f5166.firebaseapp.com',
    storageBucket: 'easy-shopping-f5166.appspot.com',
    measurementId: 'G-FL2B2BS78N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaWhNNhiiEbzxh8keodcCUz1YJsiigylA',
    appId: '1:372284465765:android:f4ecd9301fddea1eb8dc8c',
    messagingSenderId: '372284465765',
    projectId: 'easy-shopping-f5166',
    storageBucket: 'easy-shopping-f5166.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMdOoojzcd3AGhYb4x4YW6zPy5Q6VaocI',
    appId: '1:372284465765:ios:1cea580bfbacb627b8dc8c',
    messagingSenderId: '372284465765',
    projectId: 'easy-shopping-f5166',
    storageBucket: 'easy-shopping-f5166.appspot.com',
    iosBundleId: 'com.example.eCom',
  );
}
